"""empty message

Revision ID: 512d457d8e4e
Revises: 
Create Date: 2024-10-31 17:20:06.087606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512d457d8e4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_list_api_development',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_list_api_development')
    op.drop_table('goal')
    # ### end Alembic commands ###
